---
- name: build vm with Packer
  command: "packer build -var-file {{ item.packer_varfile }} {{ item.packer_template }}"
  args:
    chdir: "/data/templates"
  become: false

- name: get qcow name
  find:
    path: "/data/templates/output-qemu"
  register: qemu_output

- name: import VM in libvirt
  include_role:
    name: install_guest
  vars:
    guest_path: "{{ qemu_output.files[0].path }}"

- name: remove output-qemu
  file:
    path: /data/templates/output-qemu
    state: absent

# we don't need to keep the cache for another build
# and we need to be savy on disk space here
- name: remove packer cache
  file:
    path: /data/templates/packer_cache
    state: absent

- name: ensure libvmi config dir is present
  file:
    path: /etc/libvmi
    state: directory

- name: check if vm has a rekall profile
  local_action: stat path="{{ role_path }}/files/{{ item.name }}-profile.json"
  register: vm_profile
  become: false

- name: install vm rekall profile
  copy:
    src: "files/{{ item.name }}-profile.json"
    dest: "/etc/libvmi/{{ item.name}}-profile.json"
  when: vm_profile.stat.exists

- name: install libvmi config entry
  blockinfile:
    path: '/etc/libvmi.conf'
    block: "{{ lookup('file', 'files/'+item.name+'.conf')}}"
    marker: ""
    state: present
    create: yes
