---
- hosts: all
  become: true
  pre_tasks:
    - name: get kernel version
      command: uname -r
      register: uname

    - name: display kernel version
      debug:
        var: uname.stdout

    - name: fix permissions on kvm node
      file:
        path: /dev/kvm
        owner: root
        group: kvm
        mode: 0666
  roles:
    - remote
    - packer
    - libvirt
    - qemu
    - name: hvmi
      when: hvmi
    - name: libvmi
      when: not hvmi
    - name: vm
