---
- hosts: all
  become: true
  pre_tasks:
    - name: get kernel version
      command: uname -r
      register: uname

    - name: display kernel version
      debug:
        var: uname.stdout

    - name: install Packer
      apt:
        name: packer
        state: present

    - name: fix permissions on kvm node
      file:
        path: /dev/kvm
        owner: root
        group: kvm
        mode: 0666
  roles:
    - remote
    - qemu
    - libvirt
    - name: libvmi
      when: not hvmi
    - name: vm
      when: not hvmi
