---
- name: update cache
  apt:
    update_cache: yes

- name: install build dependencies
  package:
    name: "{{ item }}"
  with_items:
    - bc
    - fakeroot
    - dpkg-dev
    - flex
    - bison
    - libelf-dev
    - libssl-dev

# because of Windows filesystem restrictions, the KVM repo cannot be checked out on Windows
# it contains some files like
# - drivers/gpu/drm/nouveau/nvkm/subdev/i2c/aux.c
# - drivers/gpu/drm/nouveau/nvkm/subdev/i2c/aux.h
# - include/soc/arc/aux.h
# etc..
# see: https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN#naming-conventions
- name: Perform initial checkout of KVM (only when running on Windows)
  command: git submodule update --init kvm
  args:
    chdir: "{{ root_dir }}"
  become: false
  when: is_windows

- name: configure kernel using distro's config
  command: make olddefconfig
  args:
    chdir: "{{ root_dir }}/kvm"
  become: false

# disable trusted keys debian/certs/debian-uefi-certs.pem
# as they are only available in the kernel sources, and we don't
# care about SecureBoot
- name: disable SYSTEM_TRUSTED_KEYS
  command: ./scripts/config --disable SYSTEM_TRUSTED_KEYS
  args:
    chdir: "{{ root_dir }}/kvm"
  become: false

- name: disable MODULE_SIG_KEY
  command: ./scripts/config --disable MODULE_SIG_KEY
  args:
    chdir: "{{ root_dir }}/kvm"
  become: false

# configure KVM
- name: enable KVM
  command: ./scripts/config --enable KVM
  args:
    chdir: "{{ root_dir }}/kvm"
  become: false

- name: enable KVM_INTEL
  command: ./scripts/config --enable KVM_INTEL
  args:
    chdir: "{{ root_dir }}/kvm"
  become: false

- name: enable KVM_AMD
  command: ./scripts/config --enable KVM_AMD
  args:
    chdir: "{{ root_dir }}/kvm"
  become: false

# KVM_INTROSPECTION depends on REMOTE_MAPPING,
# which depends on KSM being disabled
- name: disable KSM
  command: ./scripts/config --disable KSM
  args:
    chdir: "{{ root_dir }}/kvm"
  become: false

- name: enable REMOTE_MAPPING
  command: ./scripts/config --enable REMOTE_MAPPING
  args:
    chdir: "{{ root_dir }}/kvm"
  become: false

- name: enable KVM_INTROSPECTION
  command: ./scripts/config --enable KVM_INTROSPECTION
  args:
    chdir: "{{ root_dir }}/kvm"
  become: false

- name: enable KVM_INTROSPECTION_GUEST (HVMI)
  command: ./scripts/config --enable KVM_INTROSPECTION_GUEST
  args:
    chdir: "{{ root_dir }}/kvm"
  become: false
  when: hvmi

- name: disable TRANSPARENT_HUGEPAGE (HVMI)
  command: ./scripts/config --disable TRANSPARENT_HUGEPAGE
  args:
    chdir: "{{ root_dir }}/kvm"
  become: false
  when: hvmi

- name: append -kvmi to kernel version string
  lineinfile:
    dest: "{{ root_dir }}/kvm/Makefile"
    regexp: '^EXTRAVERSION ='
    line: 'EXTRAVERSION = -kvmi'
  become: false

- name: set default config to new options
  command: make olddefconfig
  args:
    chdir: "{{ root_dir }}/kvm"
  become: false

- name: install kvm
  include: install_deb.yml
  when: kvm_install_package

- name: install kvm
  include: install_normal.yml
  when: not kvm_install_package

- name: set kvmi kernel as default
  lineinfile:
    dest: /etc/default/grub
    regexp: '^GRUB_DEFAULT'
    line: 'GRUB_DEFAULT="1>0"'

- name: update GRUB configuration
  command: update-grub

- name: Ensure /etc/modules-load.d/ directory exists
  file:
    path: /etc/modules-load.d/
    state: directory
  when: hvmi

- name: Create vhost-vsock.conf
  copy:
    src: vhost-vsock.conf
    dest: /etc/modules-load.d/
  when: hvmi

- name: Ensure /etc/udev/rules.d/ directory exists
  file:
    path: /etc/udev/rules.d/
    state: directory
  when: hvmi

- name: Create 10-vhost-vsock.rules
  copy:
    src: 10-vhost-vsock.rules
    dest: /etc/udev/rules.d/
  when: hvmi

- name: Update all initrd images
  command: update-initramfs -k all -u
  when: hvmi

- name: setup libkvmi
  include: libkvmi.yml
